# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('myinfo', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
