# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_auto_20180830_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info',
            name='identity',
            field=models.CharField(max_length=200),
        ),
    ]
