# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='identity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='test2/photos'),
        ),
    ]
