# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0005_auto_20180830_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
