# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0006_auto_20180831_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=200)),
                ('my_roles', models.ManyToManyField(to='test2.Member_info')),
            ],
        ),
        migrations.CreateModel(
            name='My_under',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=200)),
                ('my_unders', models.ManyToManyField(to='test2.Member_info')),
            ],
        ),
    ]
