# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0007_my_role_my_under'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_under',
            name='my_unders',
        ),
        migrations.AlterField(
            model_name='my_role',
            name='my_roles',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
