# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0008_auto_20180902_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_under',
            name='my_unders',
            field=models.ManyToManyField(to='test2.Member_info'),
        ),
        migrations.AlterField(
            model_name='my_role',
            name='my_roles',
            field=models.ManyToManyField(to='test2.Member_info'),
        ),
    ]
