# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0009_auto_20180902_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
