# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0011_auto_20180904_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_info',
            name='my_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
